### ISSUE TITLE
Seems to hang in win8 env

### ISSUE THREAD

**Issue by dz0ny** [dz0ny/gobu#2]
CC @slax0rr

**Comment by slax0rr** [comment]
Tried it home, on Windows 7, it does not hang, but it downloads the tar which can not be extracted natively. Extracting with Windows command line tools will be difficult, maybe just download the .msi installer and execute it?

**Comment by dz0ny** [comment]
Untar should work since it uses native method 

see https://github.com/dz0ny/gobu/blob/master/src/gobu/main.go#L4

**Comment by slax0rr** [comment]
Well, this is the output after running it:

```
D:\Users\slax0r\Downloads>gobu-windows-amd64.exe
2016/02/03 22:33:54 Local path: C:\Users\slax0r\.gobu\1.5.2.tar.gz
2016/02/03 22:33:54 Online path: https://storage.googleapis.com/golang/go1.5.2.w
indows-amd64.tar.gz
2016/02/03 22:33:54 Target path: C:\Users\slax0r\.gobu\1.5.2
2016/02/03 22:33:54 gzip: invalid header
```

**Comment by m0veax** [comment]
Hey i saw this issue today and thought i could give some feedback to Windows 10.

Seems that the link for the toolchain download won't work:

```
D:\downloads>gobu-Windows-x86_64.exe
2016/09/14 23:30:12 Local path: C:\Users\ghoulsen\.gobu\1.7.tar.gz
2016/09/14 23:30:12 Online path: https://storage.googleapis.com/golang/go1.7.windows-amd64.tar.gz
2016/09/14 23:30:12 Target path: C:\Users\ghoulsen\.gobu\1.7
2016/09/14 23:30:12 go toolchain download: https://storage.googleapis.com/golang/go1.7.windows-amd64.tar.gz is not there
```

If i can provide some more informations, just leave me a note :)

**Comment by dz0ny** [comment]
Yep, windows releases are packaged in zip and that part is not done yet, but should be easily to add via https://golang.org/pkg/archive/zip/

**Comment by m0veax** [comment]
I've never done golang, but maybe @slax0rr would support me with a review while fixing that. I'll try to take a look at the weekend :) Would be a chance to get in touch with go

**Comment by dz0ny** [comment]
One small sugestion http://stackoverflow.com/questions/19847594/how-to-reliably-detect-os-platform-in-go

**Comment by m0veax** [comment]
Yeah, runtime.GOOS was what i've noticed for doing that. Thanks for the suggestion.

Feel free to assign me to that issue.

**Comment by m0veax** [comment]
Hey, i've started fixing this but did not came to an end.

https://github.com/m0veax/gobu/commit/f6ca4fe1ba7fe9fed3b345b02bba45bfa2915aae

I would like to make an unzip command as like your untar command. If you are not in a hurry, i would do this over the next week.

**Comment by m0veax** [comment]
I've managed the download and unzip part.

Now i am getting this error:

```
D:\>gobu.exe
2016/09/21 00:08:46 Skipping download
2016/09/21 00:08:46 >> You are now in a new GOBU shell. To exit, type 'exit'
2016/09/21 00:08:46 exec: "": executable file not found in %PATH%
panic: exec: "": executable file not found in %PATH%

goroutine 1 [running]:
panic(0x5fe440, 0xc0420c7270)
        C:/Go/src/runtime/panic.go:500 +0x1af
log.Panic(0xc042077d60, 0x1, 0x1)
        C:/Go/src/log/log.go:320 +0xd0
main.resolveBinary(0x0, 0x0, 0x0, 0x0)
        D:/golang/gobu/src/gobu/main.go:68 +0xf0
main.runShell(0x650f60, 0x3)
        D:/golang/gobu/src/gobu/main.go:58 +0x14b
main.main()
        D:/golang/gobu/src/gobu/main.go:135 +0x3a9
```

Any idea how to fix that? I would like to fix that too. I would create a pull request if that is fixed.

**Comment by dz0ny** [comment]
In linux it picks up shell from env variable, in win it has to be the same as parent process (or cmd.exe in most cases)

**Comment by m0veax** [comment]
Thanks for the advice, i will have a look at it later :)
