### ISSUE TITLE
Listing available go versions

### ISSUE THREAD

**Issue by m0veax** [dz0ny/gobu#7]
A similar project for managing perl versions is perlbrew.

You find informations here:
- http://perlbrew.pl
- https://metacpan.org/pod/App::perlbrew

There you can get a list of availabe perl versions by a cli command. Further it is possible to switch the perl version in an shell environment and there is even a documentation to prefer the perlbrew choosen perl version over the system installed perl version by modifing the .bashrc

Maybe those are features which would give that project a boost.

We could start with listing the available go versions by adding a command for it

**Comment by cixtor** [comment]
I have a proposal to implement this feature. The official repository for Go is hosted at _"Google Source"_, there is a page with a list of references for each tagged version of the project. However, the list is pretty big considering that it also lists the beta and release candidates for each major version, as well as the weekly builds. Here is a list of the number of references and the regular expression for their names:

| Total | Type | RegExp |
| --- | --- | --- |
| 7 | major | `go[0-9]+\.[0-9]+` |
| 21 | minor | `go[0-9]+\.[0-9]+\.[0-9]+` |
| 19 | RC | `go[0-9]+\.[0-9]+rc[0-9]+` |
| 10 | beta | `go[0-9]+\.[0-9]+beta[0-9]+` |
| 100 | weekly* | `weekly(\.[0-9\-\.]{10,12})?` |
| 12 | alphas | `release\.r[0-9\.]+` |

*_(Notice that the Go team seemed to have stopped the release of weekly builds after 27 Mar, 2012. If Gobu will only support newer — maybe stable — versions then ignoring the weekly and alpha releases will cut out a significant portion of the data)_

My idea is to send a GET request to this page: [go/go/+refs](https://go.googlesource.com/go/+refs) and extract the version names from the HTML code using simple text manipulation to avoid expensive regular expressions. However, if I were to scan the page today the code would print around 170 entries. I would like to know what is the expected output so I can skip the unnecessary versions _(maybe the oldest ones?)_. Another option would be to print the major and minor versions, then create a new flag that allows the user to print the more obscure names like the weekly releases and another flag for the release candidates.

What if the user only wants to see the releases under certain major version? Is this program expected to support filters? If yes then we need to define the format for the filters, for example, if the user wants to see all the releases associated to a specific major version then the program should print something like this:

```
$ gobu -version >=1.7
go1.7
go1.7.1
go1.7beta1
go1.7beta2
go1.7rc1
go1.7rc2
go1.7rc3
go1.7rc4
go1.7rc5
go1.7rc6
```

Let me know what do you think.

**Comment by dz0ny** [comment]
I was thinking about parsing https://golang.org/dl/ as most of the folk is only interested in current stable vesions and rc. Which is aslo show on same page...

**Comment by cixtor** [comment]
Makes sense, the official download page currently displays 20 versions which can be extracted from the HTML code using `<div class="toggle(Visible)?" id="go`. Additional to this feature I can also change the value for `globalVersion` — which is currently hardcoded — to use the latest version available. What about the cache, is it necessary? I mean, new stable versions are not released so frequently to make the program communicate with the download page to see what is the latest version available, but there is also no guarantee that a security fix will be available one day after a major version bump, so are you okay with adding a cache for this number or do you prefer to keep the program as it currently is?

**EDIT:** I created a preliminary PR to [list available Go versions](https://github.com/dz0ny/gobu/pull/8), please review.

**Comment by dvrkps** [comment]
Why not use list from https://storage.googleapis.com/golang ?
